using System;
using System.Collections.Generic;
using System.Linq;

namespace BidFX.Public.API.Price.Subject
{
    public class CommonComponents
    {
        public const string Stream = "Stream";
        public const string Quote = "Quote";
        public const string Spot = "Spot";
        public const string Outright = "Outright";
        public const string Forward = Outright;
        public const string Swap = "Swap";
        public const string NDS = "NDS";
        public const string NDF = "NDF";
        public const string Fx = "Fx";
        public const string FXTS = "FXTS";
        public const string Cross = "Cross";
        public const string Indi = "Indi";
        public const string PremiumFX = "PremiumFX";
        
        internal static readonly string[] CommonKeys =
        {
            "Access",
            "Account",
            "Algorithm",
            "AssetClass",
            "BondType",
            "CorpID",
            "Currency",
            "Customer",
            "Dealer",
            "DealerCount",
            "EndTime",
            "EndTimeIsRelative",
            "Exchange",
            "ExpiryDate",
            "FunctionName",
            "LegCount",
            "LegClass",
            "Level",
            "Market",
            "Punctuality",
            "PutCall",
            "Quantity",
            "QueryType",
            "QuoteGroupId",
            "QuoteStyle",
            "RequestedFields",
            "Route",
            "Service",
            "SettlementDate",
            "SettlementType",
            "Side",
            "LiquidityProvider",
            "StartTime",
            "StartTimeIsRelative",
            "StrategyType",
            "Strike",
            "DealType",
            "Supplier",
            "Symbol",
            "SymbolType",
            "Tenor",
            "User",
            "ValueDate",
            "Version",

            // Tube components
            "client",
            "namespace",
            "targetcompid",
            "sendercompid",
            "eti",
            "destination",
        };

        internal static readonly string[] CommonValues =
        {
            // AssetClasses
            "Bond",
            "Convertible",
            "Equity",
            "FixedIncome",
            "Future",
            Fx,
            "Index",
            "Option",
            "Options",
            "Strategy",
            "Warrant",
            "Default",

            // Exchanges
            "AMS",
            "AOE",
            "ARC",
            "ASE",
            "ASX",
            "ATH",
            "BAO",
            "BAT",
            "BDV",
            "BER",
            "BFX",
            "BGC",
            "BMF",
            "BOS",
            "BOX",
            "BRU",
            "BSE",
            "BUD",
            "CBO",
            "CPH",
            "CVE",
            "DJI",
            "DUS",
            "EOE",
            "EUX",
            "FKA",
            "FRA",
            "FSI",
            "GBX",
            "GER",
            "GLX",
            "HAM",
            "HAN",
            "HEL",
            "HFE",
            "HKG",
            "INS",
            "IPE",
            "ISE",
            "ISO",
            "IST",
            "JKT",
            "JNB",
            "JSD",
            "JSE",
            "KAB",
            "KFE",
            "KLF",
            "KLS",
            "KOE",
            "KSC",
            "LIF",
            "LIS",
            "LME",
            "LSE",
            "LUX",
            "MAD",
            "MAT",
            "MCE",
            "MEX",
            "MIL",
            "MOE",
            "MON",
            "MRV",
            "MUN",
            "NAJ",
            "NAO",
            "NAQ",
            "NAS",
            "NGO",
            "NIK",
            "NLX",
            "NMQ",
            "NSI",
            "NSQ",
            "NYF",
            "NYQ",
            "NYS",
            "NZE",
            "OBB",
            "OPQ",
            "OSA",
            "OSL",
            "OTB",
            "OTC",
            "PAO",
            "PAR",
            "PHO",
            "PHS",
            "PNK",
            "PRA",
            "PSE",
            "QMH",
            "RTS",
            "SAO",
            "SAP",
            "SES",
            "SET",
            "SFE",
            "SFX",
            "SGO",
            "SHH",
            "SIM",
            "STC",
            "STO",
            "STU",
            "STX",
            "SWX",
            "TAI",
            "TCE",
            "TFF",
            "TGE",
            "THM",
            "TIM",
            "TLV",
            "TOR",
            "TRQ",
            "TWO",
            "TYO",
            "VIE",
            "VTX",
            "WCB",
            "WSE",
            "XPH",

            // Levels
            "1",
            "2",
            "3",
            "4",
            "Depth",
            "Indicative",
            "Regional",
            "TimeAndSales",
            "Volumes",

            // Sources
            "BMF",
            "BondVision",
            "CITIFX",
            "ComStock",
            "Delayed",
            "ESpeed",
            "Eurex",
            "Galaxy",
            "ICE",
            "Indi",
            "IndiBOFA",
            "Quick",
            "RTS",
            "Reuters",
            "SWX",
            "SpryWare",
            "TSN",
            FXTS,

            // Symbols (futures and options)
            "ABBN",
            "ACE",
            "ALV",
            "ALVE",
            "AOM",
            "ARYN",
            "ASM",
            "BAEN",
            "BAY",
            "BAYE",
            "BBL",
            "BBVD",
            "BMW",
            "BNP",
            "BPT",
            "BPV",
            "BSD2",
            "BSN",
            "CBK",
            "CBKE",
            "CFR",
            "CGE",
            "CRI5",
            "DB1",
            "DBK",
            "DBKE",
            "ENL5",
            "EOA",
            "EOAE",
            "EXS1",
            "GEBN",
            "HMI",
            "HOLN",
            "HSB",
            "IES5",
            "IFX",
            "KNIN",
            "LHA",
            "LISP",
            "LONN",
            "MEO",
            "MOH",
            "MUV2",
            "NOVN",
            "ODAX",
            "ODX1",
            "ODX2",
            "ODX4",
            "ODX5",
            "OES4",
            "OES5",
            "OESX",
            "OEU3",
            "OSMI",
            "POR3",
            "PPHN",
            "ROG",
            "SCB",
            "SCHP",
            "SGE",
            "SIE",
            "SLHN",
            "SOON",
            "SUN",
            "SYNN",
            "TCO",
            "TKA",
            "TNE5",
            "TOTB",
            "TSB",
            "UBSN",
            "UHR",
            "VAC",
            "XCA",
            "ZURN",

            // Numbers and strikes
            "0",
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
            "19",
            "20",
            "21",
            "22",
            "23",
            "24",
            "25",
            "26",
            "27",
            "28",
            "29",
            "30",
            "31",
            "32",
            "33",
            "34",
            "35",
            "36",
            "37",
            "38",
            "39",
            "40",
            "41",
            "42",
            "43",
            "44",
            "45",
            "46",
            "47",
            "48",
            "49",
            "50",
            "51",
            "52",
            "53",
            "54",
            "55",
            "56",
            "57",
            "58",
            "59",
            "60",
            "61",
            "62",
            "63",
            "64",
            "65",
            "66",
            "67",
            "68",
            "69",
            "70",
            "71",
            "72",
            "73",
            "74",
            "75",
            "76",
            "77",
            "78",
            "79",
            "80",
            "81",
            "82",
            "83",
            "84",
            "85",
            "86",
            "87",
            "88",
            "89",
            "90",
            "91",
            "92",
            "93",
            "94",
            "95",
            "96",
            "97",
            "98",
            "99",
            "100",

            "Put",
            "Call",

            "Buy",
            "Sell",
            
            Stream,
            Quote,
            
            Spot,
            Forward,
            Outright,
            Swap,
            NDS,
            NDF,
            
            Cross,

            // Tube components
            "lynx",
            "tsom",
            "fixgw",
            "disco",
        };

        private static readonly Dictionary<string, string> KeyMap =
            CommonKeys.Distinct().ToDictionary(item => item, item => item);

        private static readonly Dictionary<string, string> ValueMap =
            CommonValues.Distinct().ToDictionary(item => item, item => item);

        internal static string CommonKey(string key)
        {
            try
            {
                string item;
                if (key == null || !KeyMap.TryGetValue(key, out item))
                {
                    return null;
                }
    
                return item;
            }
            catch (Exception)
            {
                return null;
            }
        }

        internal static string CommonValue(string value)
        {
            try
            {
                string item;
                if (value == null || !ValueMap.TryGetValue(value, out item))
                {
                    return null;
                }
    
                return item;
            }
            catch (Exception)
            {
                return null;
            }
        }
    }
}